using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Crm.Api.Migrations;

/// <inheritdoc />
public partial class UnifiedPersonCore : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        // ---- ensure APPTYP codes exist in ew_set (idempotent) ----
        migrationBuilder.Sql(@"
            INSERT INTO ew_set (""page"", ""pscode"", ""description"", ""status"")
            SELECT 'APPTYP', pscode, description, 1
            FROM (VALUES
                ('1', 'ERP — Pharmacy'),
                ('2', 'ERP — Shop / Market'),
                ('3', 'ERP — Restaurant'),
                ('4', 'ERP — Company'),
                ('5', 'CRM'),
                ('6', 'Clinical Management'),
                ('7', 'SPA / Hair Salon / Garage')
            ) AS v(pscode, description)
            WHERE NOT EXISTS (
                SELECT 1 FROM ew_set WHERE ""page"" = 'APPTYP' AND ""pscode"" = v.pscode
            );
        ");

        // ---- add app_type to existing ew_profile (if the table exists) ----
        // The ew_profile table already exists in crm_db from the legacy schema.
        // We add app_type defaulting to 4 (CRM) for rows that have no explicit mapping,
        // then backfill from classtyp where a matching APPTYP code exists.
        migrationBuilder.Sql(@"
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'ew_profile') THEN
                    ALTER TABLE ew_profile ADD COLUMN IF NOT EXISTS app_type SMALLINT NOT NULL DEFAULT 4;
                    UPDATE ew_profile
                    SET app_type = CASE
                        WHEN classtyp = 1 THEN 1
                        WHEN classtyp = 2 THEN 2
                        WHEN classtyp = 3 THEN 6
                        WHEN classtyp = 4 THEN 5
                        ELSE 4
                    END
                    WHERE app_type = 4
                      AND classtyp IS NOT NULL
                      AND EXISTS (SELECT 1 FROM ew_set WHERE ""page"" = 'APPTYP' AND ""pscode"" = classtyp::text);
                END IF;
            END $$;
        ");

        // ---- create unified tables ----

        // audit_log
        migrationBuilder.CreateTable(
            name: "audit_log",
            columns: table => new
            {
                id = table.Column<int>(type: "integer", nullable: false)
                    .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                person_id = table.Column<int>(type: "integer", nullable: true),
                event_type = table.Column<string>(type: "character varying(60)", maxLength: 60, nullable: false),
                detail = table.Column<string>(type: "text", nullable: true),
                ip_address = table.Column<string>(type: "character varying(45)", maxLength: 45, nullable: true),
                user_agent = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                created_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()")
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_audit_log", x => x.id);
                table.ForeignKey(
                    name: "FK_audit_log_persons_person_id",
                    column: x => x.person_id,
                    principalTable: "persons",
                    principalColumn: "id",
                    onDelete: ReferentialAction.SetNull);
            });

        // ew_profile (may already exist; CREATE IF NOT EXISTS handles that)
        migrationBuilder.Sql(@"
            CREATE TABLE IF NOT EXISTS ew_profile (
                phcyid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                phtype SMALLINT,
                description VARCHAR(255),
                ctfstname VARCHAR(50),
                ctmidname VARCHAR(50),
                ctlstname VARCHAR(50),
                title SMALLINT,
                country SMALLINT,
                territory SMALLINT,
                city SMALLINT,
                street VARCHAR(255),
                building VARCHAR(50),
                floor VARCHAR(50),
                pobox VARCHAR(50),
                phone VARCHAR(50),
                mobile VARCHAR(50),
                fax VARCHAR(50),
                email VARCHAR(50),
                classtyp SMALLINT,
                app_type SMALLINT NOT NULL DEFAULT 4,
                phsid INTEGER,
                remarks VARCHAR(255),
                moh_num VARCHAR(20),
                mof_num VARCHAR(20),
                vat_num VARCHAR(20),
                ssn_num VARCHAR(20),
                ph_lic_num VARCHAR(20),
                ph_lic_date TIMESTAMP,
                oper_id INTEGER,
                form_id INTEGER,
                timest TIMESTAMP
            );
        ");
        migrationBuilder.CreateIndex(
            name: "IX_ew_profile_app_type",
            table: "ew_profile",
            column: "app_type");
        migrationBuilder.CreateIndex(
            name: "IX_ew_profile_email",
            table: "ew_profile",
            column: "email",
            filter: "email IS NOT NULL");

        // ew_set (lookup)
        migrationBuilder.CreateTable(
            name: "ew_set",
            columns: table => new
            {
                page = table.Column<string>(type: "character varying(5)", maxLength: 5, nullable: false),
                pscode = table.Column<string>(type: "character varying(5)", maxLength: 5, nullable: false),
                uscode = table.Column<string>(type: "character varying(5)", maxLength: 5, nullable: true),
                description = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                status = table.Column<short>(type: "smallint", nullable: true),
                usref = table.Column<int>(type: "integer", nullable: true),
                descref = table.Column<int>(type: "integer", nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_ew_set", x => new { x.page, x.pscode });
            });

        // ew_prfset (profile settings)
        migrationBuilder.CreateTable(
            name: "ew_prfset",
            columns: table => new
            {
                phcyid = table.Column<int>(type: "integer", nullable: false),
                termid = table.Column<short>(type: "smallint", nullable: false),
                rcp_temp = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                rcp_print = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                rcp_prn_sal = table.Column<bool>(type: "boolean", nullable: true),
                ssn_temp = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                ssn_print = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                lbl_temp = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                lbl_print = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                bcd_temp = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                bcd_print = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                curr1 = table.Column<short>(type: "smallint", nullable: true),
                curr2 = table.Column<short>(type: "smallint", nullable: true),
                fx_rate = table.Column<decimal>(type: "numeric", nullable: true),
                vat_rate = table.Column<decimal>(type: "numeric", nullable: true),
                opn_cash = table.Column<decimal>(type: "numeric", nullable: true),
                ssn_rsv = table.Column<int>(type: "integer", nullable: true),
                drw_com = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                bck_time = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: true),
                bck_cnt = table.Column<int>(type: "integer", nullable: true),
                bck_path = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                oper_id = table.Column<int>(type: "integer", nullable: true),
                form_id = table.Column<int>(type: "integer", nullable: true),
                timest = table.Column<DateTime>(type: "timestamp without time zone", nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_ew_prfset", x => new { x.phcyid, x.termid });
                table.ForeignKey(
                    name: "FK_ew_prfset_ew_profile_phcyid",
                    column: x => x.phcyid,
                    principalTable: "ew_profile",
                    principalColumn: "phcyid",
                    onDelete: ReferentialAction.Cascade);
            });

        // persons (unified person core)
        migrationBuilder.CreateTable(
            name: "persons",
            columns: table => new
            {
                id = table.Column<int>(type: "integer", nullable: false)
                    .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                profile_id = table.Column<int>(type: "integer", nullable: false),
                person_type = table.Column<short>(type: "smallint", nullable: false),
                title = table.Column<short>(type: "smallint", nullable: true),
                first_name = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                middle_name = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                last_name = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                country_id = table.Column<int>(type: "integer", nullable: true),
                territory_id = table.Column<int>(type: "integer", nullable: true),
                city_id = table.Column<int>(type: "integer", nullable: true),
                street = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                building = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                floor = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                pobox = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                phone = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                mobile = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                fax = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                email = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                class_typ = table.Column<short>(type: "smallint", nullable: true),
                status = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: false, defaultValueSql: "'1'"),
                marital_status = table.Column<short>(type: "smallint", nullable: true),
                registry_no = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: true),
                dob = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                gender = table.Column<short>(type: "smallint", nullable: true),
                remarks = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                created_by = table.Column<int>(type: "integer", nullable: true),
                created_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()"),
                updated_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()")
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_persons", x => x.id);
                table.ForeignKey(
                    name: "FK_persons_ew_profile_profile_id",
                    column: x => x.profile_id,
                    principalTable: "ew_profile",
                    principalColumn: "phcyid",
                    onDelete: ReferentialAction.Cascade);
            });

        // crm_client_extension
        migrationBuilder.CreateTable(
            name: "crm_client_extension",
            columns: table => new
            {
                person_id = table.Column<int>(type: "integer", nullable: false),
                status = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: false, defaultValueSql: "'Potential'"),
                client_type = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: false, defaultValueSql: "'Other'"),
                notes = table.Column<string>(type: "text", nullable: true),
                created_by = table.Column<int>(type: "integer", nullable: true),
                created_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()"),
                updated_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()")
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_crm_client_extension", x => x.person_id);
                table.ForeignKey(
                    name: "FK_crm_client_extension_persons_person_id",
                    column: x => x.person_id,
                    principalTable: "persons",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });

        // person_accounting
        migrationBuilder.CreateTable(
            name: "person_accounting",
            columns: table => new
            {
                id = table.Column<int>(type: "integer", nullable: false)
                    .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                person_id = table.Column<int>(type: "integer", nullable: false),
                person_type = table.Column<int>(type: "integer", nullable: false),
                seq = table.Column<short>(type: "smallint", nullable: false),
                effective_date = table.Column<DateTime>(type: "timestamp without time zone", nullable: false),
                currency = table.Column<short>(type: "smallint", nullable: true),
                period = table.Column<short>(type: "smallint", nullable: true),
                amount = table.Column<decimal>(type: "numeric(15,2)", nullable: true),
                discount = table.Column<decimal>(type: "numeric(5,2)", nullable: true),
                created_by = table.Column<int>(type: "integer", nullable: true),
                created_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()")
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_person_accounting", x => x.id);
                table.ForeignKey(
                    name: "FK_person_accounting_persons_person_id",
                    column: x => x.person_id,
                    principalTable: "persons",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });

        // person_allergies
        migrationBuilder.CreateTable(
            name: "person_allergies",
            columns: table => new
            {
                id = table.Column<int>(type: "integer", nullable: false)
                    .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                person_id = table.Column<int>(type: "integer", nullable: false),
                seq = table.Column<short>(type: "smallint", nullable: false),
                created_date = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()"),
                allergy_type = table.Column<short>(type: "smallint", nullable: true),
                item_id = table.Column<int>(type: "integer", nullable: true),
                description = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                ingredient_id = table.Column<int>(type: "integer", nullable: true),
                ingredient_desc = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                status = table.Column<short>(type: "smallint", nullable: true),
                created_by = table.Column<int>(type: "integer", nullable: true),
                created_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()")
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_person_allergies", x => x.id);
                table.ForeignKey(
                    name: "FK_person_allergies_persons_person_id",
                    column: x => x.person_id,
                    principalTable: "persons",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });

        // person_clinical
        migrationBuilder.CreateTable(
            name: "person_clinical",
            columns: table => new
            {
                id = table.Column<int>(type: "integer", nullable: false)
                    .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                person_id = table.Column<int>(type: "integer", nullable: false),
                seq = table.Column<short>(type: "smallint", nullable: false),
                visit_date = table.Column<DateTime>(type: "timestamp without time zone", nullable: false),
                persons_weight = table.Column<decimal>(type: "numeric(5,2)", nullable: true),
                persons_height = table.Column<decimal>(type: "numeric(5,2)", nullable: true),
                status = table.Column<short>(type: "smallint", nullable: true),
                created_by = table.Column<int>(type: "integer", nullable: true),
                created_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()")
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_person_clinical", x => x.id);
                table.ForeignKey(
                    name: "FK_person_clinical_persons_person_id",
                    column: x => x.person_id,
                    principalTable: "persons",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });

        // person_clinical_detail
        migrationBuilder.CreateTable(
            name: "person_clinical_detail",
            columns: table => new
            {
                id = table.Column<int>(type: "integer", nullable: false)
                    .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                person_id = table.Column<int>(type: "integer", nullable: false),
                seq = table.Column<short>(type: "smallint", nullable: false),
                clinical_id = table.Column<int>(type: "integer", nullable: false),
                clinical_type = table.Column<short>(type: "smallint", nullable: true),
                value = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: true),
                created_by = table.Column<int>(type: "integer", nullable: true),
                created_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()")
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_person_clinical_detail", x => x.id);
                table.ForeignKey(
                    name: "FK_person_clinical_detail_persons_person_id",
                    column: x => x.person_id,
                    principalTable: "persons",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });

        // person_communication
        migrationBuilder.CreateTable(
            name: "person_communication",
            columns: table => new
            {
                id = table.Column<int>(type: "integer", nullable: false)
                    .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                person_id = table.Column<int>(type: "integer", nullable: false),
                first_visit = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                com_phone = table.Column<short>(type: "smallint", nullable: false, defaultValueSql: "'0'"),
                com_sms = table.Column<short>(type: "smallint", nullable: false, defaultValueSql: "'0'"),
                com_email = table.Column<short>(type: "smallint", nullable: false, defaultValueSql: "'0'"),
                com_whapp = table.Column<short>(type: "smallint", nullable: false, defaultValueSql: "'0'"),
                created_by = table.Column<int>(type: "integer", nullable: true),
                created_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()"),
                updated_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()")
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_person_communication", x => x.id);
                table.ForeignKey(
                    name: "FK_person_communication_persons_person_id",
                    column: x => x.person_id,
                    principalTable: "persons",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });

        // person_contacts
        migrationBuilder.CreateTable(
            name: "person_contacts",
            columns: table => new
            {
                id = table.Column<int>(type: "integer", nullable: false)
                    .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                person_id = table.Column<int>(type: "integer", nullable: false),
                seq = table.Column<short>(type: "smallint", nullable: false),
                first_name = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                last_name = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                job_pos = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                phone = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                phone_ext = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: true),
                mobile = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                email = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                connect = table.Column<short>(type: "smallint", nullable: true),
                created_by = table.Column<int>(type: "integer", nullable: true),
                created_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()"),
                updated_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()")
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_person_contacts", x => x.id);
                table.ForeignKey(
                    name: "FK_person_contacts_persons_person_id",
                    column: x => x.person_id,
                    principalTable: "persons",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });

        // person_credentials (BCrypt auth)
        migrationBuilder.CreateTable(
            name: "person_credentials",
            columns: table => new
            {
                id = table.Column<int>(type: "integer", nullable: false)
                    .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                person_id = table.Column<int>(type: "integer", nullable: false),
                username = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: true),
                password_hash = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: false),
                verification_code = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: true),
                def_lang = table.Column<short>(type: "smallint", nullable: true),
                def_form = table.Column<short>(type: "smallint", nullable: true),
                access_level = table.Column<short>(type: "smallint", nullable: false),
                must_reset = table.Column<bool>(type: "boolean", nullable: false, defaultValueSql: "false"),
                created_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()"),
                updated_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()")
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_person_credentials", x => x.id);
                table.ForeignKey(
                    name: "FK_person_credentials_persons_person_id",
                    column: x => x.person_id,
                    principalTable: "persons",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });

        // person_discounts
        migrationBuilder.CreateTable(
            name: "person_discounts",
            columns: table => new
            {
                id = table.Column<int>(type: "integer", nullable: false)
                    .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                person_id = table.Column<int>(type: "integer", nullable: false),
                disc_bas_adv = table.Column<short>(type: "smallint", nullable: true),
                disc_cost = table.Column<short>(type: "smallint", nullable: true),
                disc_val = table.Column<decimal>(type: "numeric", nullable: true),
                disc_type = table.Column<short>(type: "smallint", nullable: true),
                disc_exc = table.Column<short>(type: "smallint", nullable: true),
                cost_inv = table.Column<short>(type: "smallint", nullable: true),
                disc_str = table.Column<short>(type: "smallint", nullable: true),
                created_by = table.Column<int>(type: "integer", nullable: true),
                created_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()"),
                updated_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()")
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_person_discounts", x => x.id);
                table.ForeignKey(
                    name: "FK_person_discounts_persons_person_id",
                    column: x => x.person_id,
                    principalTable: "persons",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });

        // person_family
        migrationBuilder.CreateTable(
            name: "person_family",
            columns: table => new
            {
                id = table.Column<int>(type: "integer", nullable: false)
                    .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                person_id = table.Column<int>(type: "integer", nullable: false),
                seq = table.Column<short>(type: "smallint", nullable: false),
                fam_lnk = table.Column<short>(type: "smallint", nullable: true),
                fam_id = table.Column<int>(type: "integer", nullable: true),
                fam_st = table.Column<short>(type: "smallint", nullable: true),
                created_by = table.Column<int>(type: "integer", nullable: true),
                created_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()"),
                updated_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()")
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_person_family", x => x.id);
                table.ForeignKey(
                    name: "FK_person_family_persons_person_id",
                    column: x => x.person_id,
                    principalTable: "persons",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });

        // person_images (BYTEA)
        migrationBuilder.CreateTable(
            name: "person_images",
            columns: table => new
            {
                id = table.Column<int>(type: "integer", nullable: false)
                    .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                person_id = table.Column<int>(type: "integer", nullable: false),
                fs_data = table.Column<byte[]>(type: "bytea", nullable: true),
                fs_data_guid = table.Column<Guid>(type: "uuid", nullable: false, defaultValueSql: "gen_random_uuid()"),
                fs_date_time = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()")
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_person_images", x => x.id);
                table.ForeignKey(
                    name: "FK_person_images_persons_person_id",
                    column: x => x.person_id,
                    principalTable: "persons",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });

        // person_insurance
        migrationBuilder.CreateTable(
            name: "person_insurance",
            columns: table => new
            {
                id = table.Column<int>(type: "integer", nullable: false)
                    .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                person_id = table.Column<int>(type: "integer", nullable: false),
                insurance_type = table.Column<short>(type: "smallint", nullable: false),
                seq = table.Column<short>(type: "smallint", nullable: false),
                effective_date = table.Column<DateTime>(type: "timestamp without time zone", nullable: false),
                expiry_date = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                org_id = table.Column<int>(type: "integer", nullable: true),
                ben_org_id = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                covered = table.Column<decimal>(type: "numeric", nullable: true),
                created_by = table.Column<int>(type: "integer", nullable: true),
                created_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()")
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_person_insurance", x => x.id);
                table.ForeignKey(
                    name: "FK_person_insurance_persons_person_id",
                    column: x => x.person_id,
                    principalTable: "persons",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });

        // person_loyalty
        migrationBuilder.CreateTable(
            name: "person_loyalty",
            columns: table => new
            {
                id = table.Column<int>(type: "integer", nullable: false)
                    .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                person_id = table.Column<int>(type: "integer", nullable: false),
                loy_id = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                loy_card = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                loy_points = table.Column<decimal>(type: "numeric", nullable: true),
                loy_disc = table.Column<decimal>(type: "numeric", nullable: true),
                loy_eff_date = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                loy_mod_date = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                created_by = table.Column<int>(type: "integer", nullable: true),
                created_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()"),
                updated_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()")
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_person_loyalty", x => x.id);
                table.ForeignKey(
                    name: "FK_person_loyalty_persons_person_id",
                    column: x => x.person_id,
                    principalTable: "persons",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });

        // person_prescription_reservation
        migrationBuilder.CreateTable(
            name: "person_prescription_reservation",
            columns: table => new
            {
                id = table.Column<int>(type: "integer", nullable: false)
                    .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                person_id = table.Column<int>(type: "integer", nullable: false),
                effective_date = table.Column<DateTime>(type: "timestamp without time zone", nullable: false),
                expiry_date = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                ben_id = table.Column<int>(type: "integer", nullable: true),
                item_id = table.Column<int>(type: "integer", nullable: true),
                box_qty = table.Column<short>(type: "smallint", nullable: true),
                reservation_period = table.Column<short>(type: "smallint", nullable: true),
                created_by = table.Column<int>(type: "integer", nullable: true),
                created_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()")
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_person_prescription_reservation", x => x.id);
                table.ForeignKey(
                    name: "FK_person_prescription_reservation_persons_person_id",
                    column: x => x.person_id,
                    principalTable: "persons",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });

        // person_symptoms
        migrationBuilder.CreateTable(
            name: "person_symptoms",
            columns: table => new
            {
                id = table.Column<int>(type: "integer", nullable: false)
                    .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                person_id = table.Column<int>(type: "integer", nullable: false),
                symptom_seq = table.Column<short>(type: "smallint", nullable: false),
                effective_date = table.Column<DateTime>(type: "timestamp without time zone", nullable: false),
                symptom_id = table.Column<int>(type: "integer", nullable: true),
                remarks = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                status = table.Column<short>(type: "smallint", nullable: true),
                created_by = table.Column<int>(type: "integer", nullable: true),
                created_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()")
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_person_symptoms", x => x.id);
                table.ForeignKey(
                    name: "FK_person_symptoms_persons_person_id",
                    column: x => x.person_id,
                    principalTable: "persons",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });

        // login_attempts
        migrationBuilder.CreateTable(
            name: "login_attempts",
            columns: table => new
            {
                id = table.Column<int>(type: "integer", nullable: false)
                    .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                person_id = table.Column<int>(type: "integer", nullable: true),
                email = table.Column<string>(type: "character varying(320)", maxLength: 320, nullable: true),
                ip_address = table.Column<string>(type: "character varying(45)", maxLength: 45, nullable: true),
                success = table.Column<bool>(type: "boolean", nullable: false),
                created_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false, defaultValueSql: "now()")
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_login_attempts", x => x.id);
                table.ForeignKey(
                    name: "FK_login_attempts_persons_person_id",
                    column: x => x.person_id,
                    principalTable: "persons",
                    principalColumn: "id",
                    onDelete: ReferentialAction.SetNull);
            });

        // ---- indexes ----

        migrationBuilder.CreateIndex(
            name: "idx_audit_log_event_created",
            table: "audit_log",
            columns: new[] { "event_type", "created_at" });
        migrationBuilder.CreateIndex(
            name: "idx_audit_log_person_event",
            table: "audit_log",
            columns: new[] { "person_id", "event_type" });

        migrationBuilder.CreateIndex(
            name: "idx_login_attempts_email_created",
            table: "login_attempts",
            columns: new[] { "email", "created_at" });
        migrationBuilder.CreateIndex(
            name: "idx_login_attempts_ip_created",
            table: "login_attempts",
            columns: new[] { "ip_address", "created_at" });

        migrationBuilder.CreateIndex(
            name: "idx_person_accounting_person_type_seq",
            table: "person_accounting",
            columns: new[] { "person_id", "person_type", "seq" },
            unique: true);
        migrationBuilder.CreateIndex(
            name: "idx_person_allergies_person_seq",
            table: "person_allergies",
            columns: new[] { "person_id", "seq" },
            unique: true);
        migrationBuilder.CreateIndex(
            name: "idx_person_clinical_person_seq",
            table: "person_clinical",
            columns: new[] { "person_id", "seq" },
            unique: true);
        migrationBuilder.CreateIndex(
            name: "idx_person_clinical_detail_person_seq_id",
            table: "person_clinical_detail",
            columns: new[] { "person_id", "seq", "clinical_id" },
            unique: true);
        migrationBuilder.CreateIndex(
            name: "IX_person_communication_person_id",
            table: "person_communication",
            column: "person_id",
            unique: true);
        migrationBuilder.CreateIndex(
            name: "idx_person_contacts_person_seq",
            table: "person_contacts",
            columns: new[] { "person_id", "seq" },
            unique: true);
        migrationBuilder.CreateIndex(
            name: "IX_person_credentials_person_id",
            table: "person_credentials",
            column: "person_id",
            unique: true);
        migrationBuilder.CreateIndex(
            name: "IX_person_credentials_username",
            table: "person_credentials",
            column: "username",
            filter: "username IS NOT NULL");
        migrationBuilder.CreateIndex(
            name: "IX_person_discounts_person_id",
            table: "person_discounts",
            column: "person_id");
        migrationBuilder.CreateIndex(
            name: "idx_person_family_person_seq",
            table: "person_family",
            columns: new[] { "person_id", "seq" },
            unique: true);
        migrationBuilder.CreateIndex(
            name: "idx_person_images_guid",
            table: "person_images",
            column: "fs_data_guid",
            unique: true);
        migrationBuilder.CreateIndex(
            name: "IX_person_images_person_id",
            table: "person_images",
            column: "person_id");
        migrationBuilder.CreateIndex(
            name: "idx_person_insurance_person_type_seq",
            table: "person_insurance",
            columns: new[] { "person_id", "insurance_type", "seq" },
            unique: true);
        migrationBuilder.CreateIndex(
            name: "idx_person_loyalty_person_id",
            table: "person_loyalty",
            column: "person_id");
        migrationBuilder.CreateIndex(
            name: "idx_person_prescription_reservation_person_effdate",
            table: "person_prescription_reservation",
            columns: new[] { "person_id", "effective_date" },
            unique: true);
        migrationBuilder.CreateIndex(
            name: "idx_person_symptoms_person_seq",
            table: "person_symptoms",
            columns: new[] { "person_id", "symptom_seq" },
            unique: true);
        migrationBuilder.CreateIndex(
            name: "IX_persons_email",
            table: "persons",
            column: "email",
            filter: "email IS NOT NULL");
        migrationBuilder.CreateIndex(
            name: "IX_persons_person_type",
            table: "persons",
            column: "person_type");
        migrationBuilder.CreateIndex(
            name: "IX_persons_profile_id",
            table: "persons",
            column: "profile_id");
        migrationBuilder.CreateIndex(
            name: "IX_persons_status",
            table: "persons",
            column: "status");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(name: "login_attempts");
        migrationBuilder.DropTable(name: "person_symptoms");
        migrationBuilder.DropTable(name: "person_prescription_reservation");
        migrationBuilder.DropTable(name: "person_loyalty");
        migrationBuilder.DropTable(name: "person_insurance");
        migrationBuilder.DropTable(name: "person_images");
        migrationBuilder.DropTable(name: "person_family");
        migrationBuilder.DropTable(name: "person_discounts");
        migrationBuilder.DropTable(name: "person_credentials");
        migrationBuilder.DropTable(name: "person_contacts");
        migrationBuilder.DropTable(name: "person_communication");
        migrationBuilder.DropTable(name: "person_clinical_detail");
        migrationBuilder.DropTable(name: "person_clinical");
        migrationBuilder.DropTable(name: "person_allergies");
        migrationBuilder.DropTable(name: "person_accounting");
        migrationBuilder.DropTable(name: "crm_client_extension");
        migrationBuilder.DropTable(name: "persons");
        migrationBuilder.DropTable(name: "ew_prfset");
        migrationBuilder.DropTable(name: "ew_set");
        migrationBuilder.DropTable(name: "audit_log");
        migrationBuilder.DropTable(name: "ew_profile");
    }
}
